# Generated by Django 3.1 on 2020-08-31 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('poster', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Timing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('booked_date', models.DateField(default='2020-08-31', editable=False, max_length=250)),
                ('booked_time', models.TimeField(default='11:37:52', editable=False, max_length=250)),
                ('booking_time', models.IntegerField(default=1598854072, editable=False)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moviez.movie')),
                ('timing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moviez.timing')),
            ],
        ),
    ]
