# Generated by Django 3.1 on 2020-08-28 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviez', '0004_movie_poster'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('phone', models.IntegerField()),
                ('booking_time', models.TimeField()),
            ],
        ),
    ]
