# Generated by Django 3.1 on 2020-08-28 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviez', '0006_auto_20200829_0002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='booking_time',
        ),
    ]
