# Generated by Django 3.1 on 2020-08-28 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moviez', '0007_remove_ticket_booking_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='movie',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='moviez.movie'),
        ),
    ]
