# Generated by Django 3.1 on 2020-08-28 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviez', '0008_ticket_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
