# Generated by Django 3.1 on 2020-08-28 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviez', '0009_auto_20200829_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='phone',
            field=models.CharField(max_length=12),
        ),
    ]
