# Generated by Django 3.1 on 2020-08-29 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviez', '0010_auto_20200829_0113'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='release_time',
            field=models.DateTimeField(default=None),
        ),
    ]
