# Generated by Django 3.1 on 2020-08-29 08:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('moviez', '0011_movie_release_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='release_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 29, 8, 39, 36, 625488, tzinfo=utc)),
        ),
    ]
