# Generated by Django 3.1 on 2020-08-29 10:06

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('moviez', '0014_auto_20200829_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 29, 10, 6, 20, 382374, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='movie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='moviez.movie'),
        ),
    ]
