# Generated by Django 3.1 on 2020-08-29 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviez', '0021_auto_20200829_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.TextField(),
        ),
    ]
