# Generated by Django 3.1 on 2020-08-29 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviez', '0023_auto_20200829_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='phone',
            field=models.CharField(max_length=12),
        ),
    ]
