# Generated by Django 3.1 on 2020-08-29 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moviez', '0025_auto_20200829_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='moviez.movie'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
