# Generated by Django 3.1 on 2020-08-29 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moviez', '0026_auto_20200829_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='movie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='moviez.movie'),
        ),
    ]
