# Generated by Django 3.1 on 2020-08-29 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moviez', '0027_auto_20200829_2317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='expired',
        ),
        migrations.AddField(
            model_name='ticket',
            name='booked_time',
            field=models.IntegerField(default=1598725705, editable=False),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='booking_time',
            field=models.CharField(default='2020-08-29 23:58:25', editable=False, max_length=250),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moviez.movie'),
        ),
    ]
