# Generated by Django 3.1 on 2020-08-29 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviez', '0028_auto_20200829_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='booked_time',
            field=models.IntegerField(default=1598725834, editable=False),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='booking_time',
            field=models.CharField(default='2020-08-30 00:00:34', editable=False, max_length=250),
        ),
    ]
