# Generated by Django 3.1 on 2020-08-29 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviez', '0030_auto_20200830_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='booking_time',
            field=models.IntegerField(default=1598727763, editable=False),
        ),
    ]
