# Generated by Django 3.1 on 2020-08-29 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviez', '0031_auto_20200830_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='booking_time',
            field=models.IntegerField(default=1598727848, editable=False),
        ),
    ]
