# Generated by Django 3.1 on 2020-08-29 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moviez', '0032_auto_20200830_0034'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='ticket',
            name='booking_time',
            field=models.IntegerField(default=1598732715, editable=False),
        ),
        migrations.AddField(
            model_name='movie',
            name='timings',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='moviez.timings'),
        ),
    ]
