# Generated by Django 3.1 on 2020-08-29 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviez', '0033_auto_20200830_0155'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Timings',
            new_name='Timing',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='booking_time',
            field=models.IntegerField(default=1598732794, editable=False),
        ),
    ]
