# Generated by Django 3.1 on 2020-08-29 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moviez', '0036_auto_20200830_0226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='Timing',
        ),
        migrations.AddField(
            model_name='ticket',
            name='timing',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='moviez.timing'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='booking_time',
            field=models.IntegerField(default=1598736292, editable=False),
        ),
    ]
