# Generated by Django 3.1 on 2020-08-29 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moviez', '0037_auto_20200830_0254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='booking_time',
            field=models.IntegerField(default=1598736314, editable=False),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='timing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moviez.timing'),
        ),
    ]
