# Generated by Django 3.1 on 2020-08-29 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviez', '0040_auto_20200830_0256'),
    ]

    operations = [
        migrations.AddField(
            model_name='timing',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='booking_time',
            field=models.IntegerField(default=1598737725, editable=False),
        ),
    ]
