# Generated by Django 3.1 on 2020-08-30 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviez', '0041_auto_20200830_0318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timing',
            name='count',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='booking_time',
            field=models.IntegerField(default=1598779103, editable=False),
        ),
    ]
