# Generated by Django 3.1 on 2020-08-30 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviez', '0042_auto_20200830_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='booked_date',
            field=models.CharField(default='2020-08-30', editable=False, max_length=250),
        ),
        migrations.AddField(
            model_name='ticket',
            name='booked_time',
            field=models.CharField(default='15:25:21', editable=False, max_length=250),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='booking_time',
            field=models.IntegerField(default=1598781321, editable=False),
        ),
    ]
