# Generated by Django 3.1 on 2020-08-30 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviez', '0044_auto_20200830_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='booked_time',
            field=models.TimeField(default='21:09:37', editable=False, max_length=250),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='booking_time',
            field=models.IntegerField(default=1598801977, editable=False),
        ),
    ]
