# Generated by Django 3.1 on 2020-08-30 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviez', '0045_auto_20200830_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='release_time',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='booked_time',
            field=models.TimeField(default='21:15:33', editable=False, max_length=250),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='booking_time',
            field=models.IntegerField(default=1598802333, editable=False),
        ),
    ]
